import logging

# Set up logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

LANGUAGES = {
    "English": {
        "title": "Legal Lens AI",
        "subtitle": "Your AI-powered legal document assistant",
        "language_selector": "Select Interface Language",
        "summary_language": "Select Summary Language",
        "upload_title": "Upload Legal Document",
        "upload_help": "Upload a PDF or image file (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "Extracting text from document...",
        "document_preview": "Document Preview",
        "key_people": "👥 Key People & Roles",
        "extract_roles": "Extract Names & Roles",
        "analyzing": "Analyzing document...",
        "generate_summary": "Generate Summary",
        "ai_summary": "AI-Generated Summary",
        "generate_audio": "Generate Audio",
        "generating_audio": "Generating audio...",
        "audio_version": "Audio Version",
        "error_processing": "Error processing file:",
        "error_audio": "Error generating audio:",
        "read_summary": "You can read the summary above instead.",
        "chatbot_title": "Ask Questions About Your Document",
        "chat_placeholder": "Type your question here...",
        "footer": "© 2025 Legal Lens AI. All rights reserved.",
        "no_roles_found": "No names and roles found in the document."
    },
    "Urdu": {
        "title": "لیگل لینس AI",
        "subtitle": "آپ کا AI سے چلنے والا قانونی دستاویز اسسٹنٹ",
        "language_selector": "انٹرفیس زبان منتخب کریں",
        "summary_language": "خلاصہ کی زبان منتخب کریں",
        "upload_title": "قانونی دستاویز اپ لوڈ کریں",
        "upload_help": "PDF یا تصویری فائل اپ لوڈ کریں (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "دستاویز سے متن نکالا جا رہا ہے...",
        "document_preview": "دستاویز کا پیش نظارہ",
        "key_people": "👥 اہم افراد اور کردار",
        "extract_roles": "نام اور کردار نکالیں",
        "analyzing": "دستاویز کا تجزیہ کیا جا رہا ہے...",
        "generate_summary": "خلاصہ بنائیں",
        "ai_summary": "AI سے تیار کردہ خلاصہ",
        "generate_audio": "آڈیو بنائیں",
        "generating_audio": "آڈیو تیار کیا جا رہا ہے...",
        "audio_version": "آڈیو ورژن",
        "error_processing": "فائل پروسیسنگ میں خرابی:",
        "error_audio": "آڈیو بنانے میں خرابی:",
        "read_summary": "آپ اوپر دیا گیا خلاصہ پڑھ سکتے ہیں۔",
        "chatbot_title": "اپنی دستاویز کے بارے میں سوالات پوچھیں",
        "chat_placeholder": "اپنا سوال یہاں ٹائپ کریں...",
        "footer": "© 2025 لیگل لینس AI۔ جملہ حقوق محفوظ ہیں۔",
        "no_roles_found": "دستاویز میں کوئی نام اور کردار نہیں ملا۔"
    },
    "Hindi": {
        "title": "लीगल लेंस AI",
        "subtitle": "आपका AI-संचालित कानूनी दस्तावेज़ सहायक",
        "language_selector": "इंटरफेस भाषा चुनें",
        "summary_language": "सारांश भाषा चुनें",
        "upload_title": "कानूनी दस्तावेज़ अपलोड करें",
        "upload_help": "PDF या छवि फ़ाइल अपलोड करें (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "दस्तावेज़ से पाठ निकाला जा रहा है...",
        "document_preview": "दस्तावेज़ पूर्वावलोकन",
        "key_people": "👥 प्रमुख व्यक्ति और भूमिकाएँ",
        "extract_roles": "नाम और भूमिकाएँ निकालें",
        "analyzing": "दस्तावेज़ का विश्लेषण किया जा रहा है...",
        "generate_summary": "सारांश बनाएं",
        "ai_summary": "AI-जनित सारांश",
        "generate_audio": "ऑडियो बनाएं",
        "generating_audio": "ऑडियो तैयार किया जा रहा है...",
        "audio_version": "ऑडियो संस्करण",
        "error_processing": "फ़ाइल प्रसंस्करण में त्रुटि:",
        "error_audio": "ऑडियो बनाने में त्रुटि:",
        "read_summary": "आप ऊपर दिया गया सारांश पढ़ सकते हैं।",
        "chatbot_title": "अपने दस्तावेज़ के बारे में प्रश्न पूछें",
        "chat_placeholder": "अपना प्रश्न यहां टाइप करें...",
        "footer": "© 2025 लीगल लेंस AI। सर्वाधिकार सुरक्षित।",
        "no_roles_found": "दस्तावेज़ में कोई नाम और भूमिकाएँ नहीं मिलीं।"
    },
    "Arabic": {
        "title": "لينس القانوني AI",
        "subtitle": "مساعدك القانوني المدعوم بالذكاء الاصطناعي",
        "language_selector": "اختر لغة الواجهة",
        "summary_language": "اختر لغة الملخص",
        "upload_title": "تحميل وثيقة قانونية",
        "upload_help": "قم بتحميل ملف PDF أو صورة (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "جاري استخراج النص من المستند...",
        "document_preview": "معاينة المستند",
        "key_people": "👥 الأشخاص الرئيسيون والأدوار",
        "extract_roles": "استخراج الأسماء والأدوار",
        "analyzing": "جاري تحليل المستند...",
        "generate_summary": "إنشاء ملخص",
        "ai_summary": "ملخص منشأ بواسطة الذكاء الاصطناعي",
        "generate_audio": "إنشاء صوت",
        "generating_audio": "جاري إنشاء الصوت...",
        "audio_version": "النسخة الصوتية",
        "error_processing": "خطأ في معالجة الملف:",
        "error_audio": "خطأ في إنشاء الصوت:",
        "read_summary": "يمكنك قراءة الملخص أعلاه بدلاً من ذلك.",
        "chatbot_title": "اطرح أسئلة حول مستندك",
        "chat_placeholder": "اكتب سؤالك هنا...",
        "footer": "© 2025 لينس القانوني AI. جميع الحقوق محفوظة.",
        "no_roles_found": "لم يتم العثور على أسماء وأدوار في المستند."
    },
    "French": {
        "title": "Legal Lens AI",
        "subtitle": "Votre assistant juridique propulsé par l'IA",
        "language_selector": "Sélectionner la langue de l'interface",
        "summary_language": "Sélectionner la langue du résumé",
        "upload_title": "Télécharger un document juridique",
        "upload_help": "Téléchargez un fichier PDF ou une image (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "Extraction du texte du document...",
        "document_preview": "Aperçu du document",
        "key_people": "👥 Personnes clés et rôles",
        "extract_roles": "Extraire les noms et rôles",
        "analyzing": "Analyse du document...",
        "generate_summary": "Générer un résumé",
        "ai_summary": "Résumé généré par l'IA",
        "generate_audio": "Générer l'audio",
        "generating_audio": "Génération de l'audio...",
        "audio_version": "Version audio",
        "error_processing": "Erreur lors du traitement du fichier:",
        "error_audio": "Erreur lors de la génération de l'audio:",
        "read_summary": "Vous pouvez lire le résumé ci-dessus à la place.",
        "chatbot_title": "Posez des questions sur votre document",
        "chat_placeholder": "Tapez votre question ici...",
        "footer": "© 2025 Legal Lens AI. Tous droits réservés.",
        "no_roles_found": "Aucun nom et rôle trouvé dans le document."
    },
    "Spanish": {
        "title": "Legal Lens AI",
        "subtitle": "Tu asistente legal impulsado por IA",
        "language_selector": "Seleccionar idioma de la interfaz",
        "summary_language": "Seleccionar idioma del resumen",
        "upload_title": "Subir documento legal",
        "upload_help": "Sube un archivo PDF o imagen (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "Extrayendo texto del documento...",
        "document_preview": "Vista previa del documento",
        "key_people": "👥 Personas clave y roles",
        "extract_roles": "Extraer nombres y roles",
        "analyzing": "Analizando documento...",
        "generate_summary": "Generar resumen",
        "ai_summary": "Resumen generado por IA",
        "generate_audio": "Generar audio",
        "generating_audio": "Generando audio...",
        "audio_version": "Versión de audio",
        "error_processing": "Error al procesar el archivo:",
        "error_audio": "Error al generar el audio:",
        "read_summary": "Puedes leer el resumen anterior en su lugar.",
        "chatbot_title": "Haz preguntas sobre tu documento",
        "chat_placeholder": "Escribe tu pregunta aquí...",
        "footer": "© 2025 Legal Lens AI. Todos los derechos reservados.",
        "no_roles_found": "No se encontraron nombres y roles en el documento."
    },
    "Bengali": {
        "title": "লিগাল লেন্স AI",
        "subtitle": "আপনার AI-চালিত আইনি দলিল সহায়ক",
        "language_selector": "ইন্টারফেস ভাষা নির্বাচন করুন",
        "summary_language": "সারাংশ ভাষা নির্বাচন করুন",
        "upload_title": "আইনি দলিল আপলোড করুন",
        "upload_help": "PDF বা ছবির ফাইল আপলোড করুন (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "দলিল থেকে টেক্সট বের করা হচ্ছে...",
        "document_preview": "দলিলের প্রাকদর্শন",
        "key_people": "👥 মূল ব্যক্তি এবং ভূমিকা",
        "extract_roles": "নাম এবং ভূমিকা বের করুন",
        "analyzing": "দলিল বিশ্লেষণ করা হচ্ছে...",
        "generate_summary": "সারাংশ তৈরি করুন",
        "ai_summary": "AI-উৎপাদিত সারাংশ",
        "generate_audio": "অডিও তৈরি করুন",
        "generating_audio": "অডিও তৈরি করা হচ্ছে...",
        "audio_version": "অডিও সংস্করণ",
        "error_processing": "ফাইল প্রক্রিয়াকরণে ত্রুটি:",
        "error_audio": "অডিও তৈরি করতে ত্রুটি:",
        "read_summary": "আপনি পরিবর্তে উপরের সারাংশটি পড়তে পারেন।",
        "chatbot_title": "আপনার দলিল সম্পর্কে প্রশ্ন জিজ্ঞাসা করুন",
        "chat_placeholder": "এখানে আপনার প্রশ্ন টাইপ করুন...",
        "footer": "© 2025 লিগাল লেন্স AI। সর্বস্বত্ব সংরক্ষিত।",
        "no_roles_found": "দলিলে কোন নাম এবং ভূমিকা পাওয়া যায়নি।"
    },
    "Tamil": {
        "title": "லீகல் லென்ஸ் AI",
        "subtitle": "உங்கள் AI-இயக்கும் சட்ட ஆவண உதவியாளர்",
        "language_selector": "இடைமுக மொழியைத் தேர்வு செய்க",
        "summary_language": "சுருக்க மொழியைத் தேர்வு செய்க",
        "upload_title": "சட்ட ஆவணத்தை பதிவேற்று",
        "upload_help": "PDF அல்லது பட கோப்பை பதிவேற்று (PNG, JPG, JPEG, TIFF, BMP)",
        "extracting_text": "ஆவணத்திலிருந்து உரை பிரித்தெடுக்கப்படுகிறது...",
        "document_preview": "ஆவண முன்னோட்டம்",
        "key_people": "👥 முக்கிய நபர்கள் மற்றும் பாத்திரங்கள்",
        "extract_roles": "பெயர்கள் மற்றும் பாத்திரங்களை பிரித்தெடு",
        "analyzing": "ஆவணம் பகுப்பாய்வு செய்யப்படுகிறது...",
        "generate_summary": "சுருக்கத்தை உருவாக்கு",
        "ai_summary": "AI-உருவாக்கிய சுருக்கம்",
        "generate_audio": "ஒலியை உருவாக்கு",
        "generating_audio": "ஒலி உருவாக்கப்படுகிறது...",
        "audio_version": "ஒலி பதிப்பு",
        "error_processing": "கோப்பு செயலாக்கத்தில் பிழை:",
        "error_audio": "ஒலி உருவாக்கத்தில் பிழை:",
        "read_summary": "அதற்கு பதிலாக மேலே உள்ள சுருக்கத்தை படிக்கலாம்.",
        "chatbot_title": "உங்கள் ஆவணத்தைப் பற்றி கேள்விகள் கேளுங்கள்",
        "chat_placeholder": "உங்கள் கேள்வியை இங்கே தட்டச்சு செய்யவும்...",
        "footer": "© 2025 லீகல் லென்ஸ் AI. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
        "no_roles_found": "ஆவணத்தில் பெயர்கள் மற்றும் பாத்திரங்கள் எதுவும் கிடைக்கவில்லை."
    }
}

def get_text(key, language="English"):
    """Get translated text for a given key and language."""
    try:
        return LANGUAGES.get(language, LANGUAGES["English"]).get(key, key)
    except Exception as e:
        logging.error(f"Error getting text for key '{key}' in language '{language}': {str(e)}")
        return key 